### PR TITLE
Minor cleanups

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/119)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/119)* status: 0 of 4 files reviewed, 1 unresolved discussion

___
*[DEBUGGING.md, line 33 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/119#-MS8wQxCDYF4cGXAhOyS:-MS8wQxCDYF4cGXAhOyT:bngc2ct) ([raw file](https://github.com/pmem/pmemkv-java/blob/d57a9f38c92086d6ad471f95413e920b4c8b8353/DEBUGGING.md#L33)):*
> ```Markdown
> 
> ```sh
> javac -g -cp ../target/*.jar BasicExample.java
> ```

I guess this line should also be updated, but I'm not sure how... @karczex any hints here, pls?

**Review by KFilipek — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/119)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[DEBUGGING.md, line 33 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/119#-MS8wQxCDYF4cGXAhOyS:-MSTKRAX55ByuGS_5zHp:b-4hlo7t) ([raw file](https://github.com/pmem/pmemkv-java/blob/d57a9f38c92086d6ad471f95413e920b4c8b8353/DEBUGGING.md#L33)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I guess this line should also be updated, but I'm not sure how... @karczex any hints here, pls?
</blockquote></details>

Check this, there is flag for dbg compilation. I think we can build using -Dflags
https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html
___
*[README.md, line 59 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/119#-MSTLbPY2nUuFtUR33nR:-MSTLbPY2nUuFtUR33nS:b-6lcnv8) ([raw file](https://github.com/pmem/pmemkv-java/blob/a632c81ee2c4d46494be14651eb7a9f015ebbd9c/README.md#L59)):*
> ```Markdown
> CPLUS_INCLUDE_PATH=<path_to_includes> \
> LIBRARY_PATH=<path_to_libs> \
> LD_LIBRARY_PATH=<path_to_libs> mvn install
> ```

I think we need to check correctness of this lines

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/119)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[README.md, line 59 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/119#-MSTLbPY2nUuFtUR33nR:-MSTg8hq0fmhDNIRh4bp:bozu1b2) ([raw file](https://github.com/pmem/pmemkv-java/blob/a632c81ee2c4d46494be14651eb7a9f015ebbd9c/README.md#L59)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I think we need to check correctness of this lines
</blockquote></details>

what do you mean to check correctness?

I've added these vars before refactoring pom files and it was needed. Right now I'm confident only about LD_LIB_PATH - it's still required in such case

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/119)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[README.md, line 59 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/119#-MSTLbPY2nUuFtUR33nR:-MSbtPfhBwUw9WmdouL0:b-hcrw8m) ([raw file](https://github.com/pmem/pmemkv-java/blob/a632c81ee2c4d46494be14651eb7a9f015ebbd9c/README.md#L59)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what do you mean to check correctness?

I've added these vars before refactoring pom files and it was needed. Right now I'm confident only about LD_LIB_PATH - it's still required in such case
</blockquote></details>

I mean I haven't tested how they influence building process

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/119)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[DEBUGGING.md, line 33 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/119#-MS8wQxCDYF4cGXAhOyS:-MT_3OdC3rQp4F_701fA:b1zoirh) ([raw file](https://github.com/pmem/pmemkv-java/blob/d57a9f38c92086d6ad471f95413e920b4c8b8353/DEBUGGING.md#L33)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Check this, there is flag for dbg compilation. I think we can build using -Dflags
https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html
</blockquote></details>

@kfilipek , I'm not sure what you're referring to...?

@karczex, I could make this debugging work, I believe I have still some wrong paths here, any help here, pls?
___
*[README.md, line 59 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/119#-MSTLbPY2nUuFtUR33nR:-MTZypsSCetCXsFxngTQ:b638pyg) ([raw file](https://github.com/pmem/pmemkv-java/blob/a632c81ee2c4d46494be14651eb7a9f015ebbd9c/README.md#L59)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I mean I haven't tested how they influence building process
</blockquote></details>

I've checked it all again and they seem really useful, I'd leave them here.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/119)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[DEBUGGING.md, line 33 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/119#-MS8wQxCDYF4cGXAhOyS:-MTendaH5DZpkyILhrzH:buci8xa) ([raw file](https://github.com/pmem/pmemkv-java/blob/d57a9f38c92086d6ad471f95413e920b4c8b8353/DEBUGGING.md#L33)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

@kfilipek , I'm not sure what you're referring to...?

@karczex, I could make this debugging work, I believe I have still some wrong paths here, any help here, pls?
</blockquote></details>

My current approach is to  add debug flag (-g) to example pom file. Probably setting it the way @kfilipek   mentioned is even better.  
```xml
   26                    <compilerArgs>                                                                            
   27                         <arg>-Xlint:all</arg>                                                                 
   28                         <arg>-g</arg>                                                                         
   29                     </compilerArgs>                                                                           
```
___
*[DEBUGGING.md, line 5 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/119#-MTejfy_DuQt93o9RvnM:-MTejfy_DuQt93o9RvnN:b-qhld3y) ([raw file](https://github.com/pmem/pmemkv-java/blob/c27ed52051b9341499fd0f8d48e7c8b3ce8a990b/DEBUGGING.md#L5)):*
> ```
> src/main/cpp/pom.xml
> ```
jni-binding/pom.xml
___
*[DEBUGGING.md, line 35 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/119#-MTeo6cNDCU27Jlg15qC:-MTeo6cNDCU27Jlg15qD:b-5z2au6) ([raw file](https://github.com/pmem/pmemkv-java/blob/c27ed52051b9341499fd0f8d48e7c8b3ce8a990b/DEBUGGING.md#L35)):*
> ```Markdown
> cd MixedTypesExample
> javac -g -cp target/*jar-with-dependencies.jar src/main/java/MixedTypesExample.java
> jdb -classpath ../target/*.jar:../../pmemkv-binding/target/pmemkv-1.0.0.jar -Djava.library.path=../../jni-binding/target MixedTypesExample
> ```

If you use jar-with-dependencies (generated by mvn install) you just need to pass class path to this jar and class name.

```
 jdb -classpath MixedTypesExample-1.0.0-jar-with-dependencies.jar MixedTypesExample
```
I run this command in directory, which contains MixedTypesExample-1.0.0-jar-with-dependencies.jar - which by default is pmemkv-java/examples/MixedTypesExample/target

**Review by karczex — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/119)* status: 6 of 7 files reviewed, 6 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[pom.xml, line 74 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/119#-MTevl5s77MuVMG_mPgL:-MTevl5t8XyXmLv2IRZg:bjx2lci) ([raw file](https://github.com/pmem/pmemkv-java/blob/c27ed52051b9341499fd0f8d48e7c8b3ce8a990b/pom.xml#L74)):*
> ```XML
>             <url>https://github.com/igchor</url>
>             <organization>Intel</organization>
>             <organizationUrl>https://intel.com</organizationUrl>
> ```

probably pmem.io. as in organization section 
___
*[pom.xml, line 86 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/119#-MTevsq8C6z6mhgQGdi2:-MTevsq8C6z6mhgQGdi3:b3kqx) ([raw file](https://github.com/pmem/pmemkv-java/blob/c27ed52051b9341499fd0f8d48e7c8b3ce8a990b/pom.xml#L86)):*
> ```XML
>             <url>https://github.com/kfilipek</url>
>             <organization>Intel</organization>
>             <organizationUrl>https://intel.com</organizationUrl>
> ```

.

**Review by karczex — COMMENTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/119)* status: 6 of 7 files reviewed, 6 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/119)* status: all files reviewed, 5 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[DEBUGGING.md, line 33 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/119#-MS8wQxCDYF4cGXAhOyS:-MTezXAX2O10bBhtJieA:bna5j2r) ([raw file](https://github.com/pmem/pmemkv-java/blob/d57a9f38c92086d6ad471f95413e920b4c8b8353/DEBUGGING.md#L33)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

My current approach is to  add debug flag (-g) to example pom file. Probably setting it the way @kfilipek   mentioned is even better.  
```xml
   26                    <compilerArgs>                                                                            
   27                         <arg>-Xlint:all</arg>                                                                 
   28                         <arg>-g</arg>                                                                         
   29                     </compilerArgs>                                                                           
```


</blockquote></details>

Take a look into link:
<debug>true</debug>
Also we can consider doing a debug profile:
https://maven.apache.org/guides/introduction/introduction-to-profiles.html

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/119)* status: all files reviewed, 5 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[DEBUGGING.md, line 33 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/119#-MS8wQxCDYF4cGXAhOyS:-MUNU6SD9Fbb1UAY6-Q7:b-cnkrmz) ([raw file](https://github.com/pmem/pmemkv-java/blob/d57a9f38c92086d6ad471f95413e920b4c8b8353/DEBUGGING.md#L33)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Take a look into link:
<debug>true</debug>
Also we can consider doing a debug profile:
https://maven.apache.org/guides/introduction/introduction-to-profiles.html
</blockquote></details>

debug profile is a potential future change, perhaps along with other Java versions profiles

as for -Dflags I'm not sure where and how do you want to apply them, in here? in this line? please be more precise :)
___
*[DEBUGGING.md, line 5 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/119#-MTejfy_DuQt93o9RvnM:-MUNSHC80Kgp1V9ZifRf:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/c27ed52051b9341499fd0f8d48e7c8b3ce8a990b/DEBUGGING.md#L5)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

> ```
> src/main/cpp/pom.xml
> ```
jni-binding/pom.xml
</blockquote></details>

Done.
___
*[DEBUGGING.md, line 35 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/119#-MTeo6cNDCU27Jlg15qC:-MUNUg4_9H_PtBHLONs4:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/c27ed52051b9341499fd0f8d48e7c8b3ce8a990b/DEBUGGING.md#L35)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

If you use jar-with-dependencies (generated by mvn install) you just need to pass class path to this jar and class name.

```
 jdb -classpath MixedTypesExample-1.0.0-jar-with-dependencies.jar MixedTypesExample
```
I run this command in directory, which contains MixedTypesExample-1.0.0-jar-with-dependencies.jar - which by default is pmemkv-java/examples/MixedTypesExample/target

</blockquote></details>

Done.
___
*[pom.xml, line 74 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/119#-MTevl5s77MuVMG_mPgL:-MUNWVI47qMIhlMAP3qS:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/c27ed52051b9341499fd0f8d48e7c8b3ce8a990b/pom.xml#L74)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

probably pmem.io. as in organization section 
</blockquote></details>

Done.
___
*[pom.xml, line 86 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/119#-MTevsq8C6z6mhgQGdi2:-MUNWWXG1gPtMZqiGTLd:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/c27ed52051b9341499fd0f8d48e7c8b3ce8a990b/pom.xml#L86)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/119#-:-MUNb8p_Cms5-QggU0za:bnfp4nl)* status: 5 of 7 files reviewed, 5 unresolved discussions (waiting on @karczex and @KFilipek)

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/119#-:-MUTA4QR6dD7fi5LjNox:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @karczex)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/119)* status: all files reviewed, 5 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[DEBUGGING.md, line 33 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/119#-MS8wQxCDYF4cGXAhOyS:-MUUBvkiExjMUjkl07Oo:b171vry) ([raw file](https://github.com/pmem/pmemkv-java/blob/d57a9f38c92086d6ad471f95413e920b4c8b8353/DEBUGGING.md#L33)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

debug profile is a potential future change, perhaps along with other Java versions profiles

as for -Dflags I'm not sure where and how do you want to apply them, in here? in this line? please be more precise :)
</blockquote></details>

@kfilipek ping ^^ The above issue is not resolved yet, I was counting on your input on this...

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/119)* status: all files reviewed, 5 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[DEBUGGING.md, line 33 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/119#-MS8wQxCDYF4cGXAhOyS:-MUdsqT_EMsiam7wnNHR:bmb8scb) ([raw file](https://github.com/pmem/pmemkv-java/blob/d57a9f38c92086d6ad471f95413e920b4c8b8353/DEBUGGING.md#L33)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

@kfilipek ping ^^ The above issue is not resolved yet, I was counting on your input on this...
</blockquote></details>

I don't remember what I had in mind then xD

**Review by KFilipek — COMMENTED** [review]
Still :lgtm:

> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/119#-:-MVRhHTC33GfoiwIDRtR:b-2pygyf)* status: all files reviewed, 4 unresolved discussions (waiting on @karczex)

**Review by KFilipek — APPROVED** [review]

**Pull request merged**
