### PR TITLE
Cleanup utils and CI

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/116)

### CODE REVIEW

**Review by karczex — COMMENTED** [review]
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/116)* status: 1 of 14 files reviewed, all discussions resolved

**Review by KFilipek — COMMENTED** [review]
> Reviewed 7 of 14 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/116)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[CONTRIBUTING.md, line 77 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/116#-MS2C3a2EQwRD9F7BEiq:-MS2C3a41qTP2C6AUSt_:b-n132fs) ([raw file](https://github.com/pmem/pmemkv-java/blob/f024f1280097da6236e243d31b8df791d6afe020/CONTRIBUTING.md#L77)):*
> ```Markdown
> the repository has to be properly configured.
> 
> * [Personal access token](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) for Github account has to be generated.
> ```

*GitHub
___
*[CONTRIBUTING.md, line 83 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/116#-MS2CWwkElcY8Tci216v:-MS2CWwkElcY8Tci216w:btju8fc) ([raw file](https://github.com/pmem/pmemkv-java/blob/f024f1280097da6236e243d31b8df791d6afe020/CONTRIBUTING.md#L83)):*
> ```Markdown
> 
> * `DOC_UPDATE_BOT_NAME` secret variable has to be set. In most cases it will be
>   the same as Github account name.
> ```

GitHub
___
*[CONTRIBUTING.md, line 85 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/116#-MS2CtqaEeeDzl31HlFH:-MS2CtqbAR1boHy9XLh_:b5e2d3h) ([raw file](https://github.com/pmem/pmemkv-java/blob/f024f1280097da6236e243d31b8df791d6afe020/CONTRIBUTING.md#L85)):*
> ```Markdown
>   the same as Github account name.
> 
> * `DOC_REPO_OWNER` secret variable has to be set. Name of Github account,
> ```

GitHub and other occurences

**Review by igchor — APPROVED** [review]
> Reviewed 1 of 14 files at r1, 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/116)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/116)* status: 14 of 15 files reviewed, 3 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[CONTRIBUTING.md, line 77 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/116#-MS2C3a2EQwRD9F7BEiq:-MS2NqyyCmerSXxLqrrP:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/f024f1280097da6236e243d31b8df791d6afe020/CONTRIBUTING.md#L77)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

*GitHub
</blockquote></details>

Done.
___
*[CONTRIBUTING.md, line 83 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/116#-MS2CWwkElcY8Tci216v:-MS2NrEYCLrH_2NbrPTY:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/f024f1280097da6236e243d31b8df791d6afe020/CONTRIBUTING.md#L83)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

GitHub
</blockquote></details>

Done.
___
*[CONTRIBUTING.md, line 85 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/116#-MS2CtqaEeeDzl31HlFH:-MS2NrQgApdwWDHjWQq5:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/f024f1280097da6236e243d31b8df791d6afe020/CONTRIBUTING.md#L85)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

GitHub and other occurences
</blockquote></details>

Done.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/116)* status: 14 of 15 files reviewed, 8 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[utils/docker/pull-or-rebuild-image.sh, line 7 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/116#-MS2k0Vu3RvrTrQleefU:-MS2k0Vu3RvrTrQleefV:bh710ap) ([raw file](https://github.com/pmem/pmemkv-java/blob/5c8f4c0da2972f0f43a8f223a1b478efbd7921c8/utils/docker/pull-or-rebuild-image.sh#L7)):*
> ```Shell
> #
> # pull-or-rebuild-image.sh - rebuilds the Docker image used in the
> #		current build (if necessary) or pulls it from the Docker Container.
> ```

container registry
___
*[utils/docker/images/prepare-pmemkv.sh, line 18 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/116#-MS2pgGUDEtofF0O9S55:-MS2pgGUDEtofF0O9S56:b-5l5tsj) ([raw file](https://github.com/pmem/pmemkv-java/blob/5c8f4c0da2972f0f43a8f223a1b478efbd7921c8/utils/docker/images/prepare-pmemkv.sh#L18)):*
> ```Shell
> 
> # stable-1.0: 1.0.3; 06.10.2020
> stable_1_pmemkv_version="77ae3ef23dc2b2db9c012dc343b125a785a0ffbc"
> ```

what's wrong with:
``` 
0f04364ea6723ad17a8c28c5f1d833abf15ff19b refs/tags/1.0.3 
```
?

If we really want to use other commit than release, please add some comment why.
___
*[utils/docker/images/prepare-pmemkv.sh, line 21 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/116#-MS2q-Kb0FXSl88zE0fI:-MS2q-Kb0FXSl88zE0fJ:b-ascu9n) ([raw file](https://github.com/pmem/pmemkv-java/blob/5c8f4c0da2972f0f43a8f223a1b478efbd7921c8/utils/docker/images/prepare-pmemkv.sh#L21)):*
> ```Shell
> 
> # stable-1.1: Merge pull request #661 from lukaszstolarczuk/fix-g...; 18.11.2020
> stable_1_1_pmemkv_version="2f727968c157c2479cf5a878b4c681fd38698a0f"
> ```

```
ccfd6d1c6e63dbc38b6853624716d37a2f647b6d refs/tags/1.1 
``` 
?
___
*[utils/docker/images/prepare-pmemkv.sh, line 24 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/116#-MS2q4ooBW0KvdAKV0W6:-MS2q4ooBW0KvdAKV0W7:b-8dqoc1) ([raw file](https://github.com/pmem/pmemkv-java/blob/5c8f4c0da2972f0f43a8f223a1b478efbd7921c8/utils/docker/images/prepare-pmemkv.sh#L24)):*
> ```Shell
> 
> # stable-1.2: Merge pull request #857 from lukaszstolarczuk/fix-c...; 16.12.2020
> stable_1_2_pmemkv_version="877dbdd327b6beae49320d21d2eb04385049ee2b"
> ```

```
41c8cc0c6059c31bd8623f84957bd24fc8a38141 refs/tags/1.2
```
?
___
*[utils/docker/images/prepare-pmemkv.sh, line 27 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/116#-MS2qAjlDrrds6qZSnSc:-MS2qAjlDrrds6qZSnSd:b2ekus4) ([raw file](https://github.com/pmem/pmemkv-java/blob/5c8f4c0da2972f0f43a8f223a1b478efbd7921c8/utils/docker/images/prepare-pmemkv.sh#L27)):*
> ```Shell
> 
> # stable-1.3: Merge pull request #864 from pmem/stable-1.2; 16.12.2020
> stable_1_3_pmemkv_version="20e10a621ebf4ccd845a0dc5bac36e24f2a31e0e"
> ```

```
399e61b6a166a28b1ef7b12f7621616b4866776d refs/tags/1.3
```
?

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/116#-:-MS2rFgV-1_h0IyKZbuR:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @lukaszstolarczuk)

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/116#-:-MS3t4XxC2sm4_D7KTyV:bnfp4nl)* status: 13 of 15 files reviewed, all discussions resolved (waiting on @KFilipek)

**Comment by lukaszstolarczuk** [comment]
I made one small change - since this is going to stable-1.0 branch IMG_VER should be set to 1.0 (not latest) and as we established, stable branch should always rebuild. (these changes are similar to what is described in RELEASE_STEPS)

**Review by karczex — COMMENTED** [review]
> Reviewed 5 of 14 files at r1, 5 of 7 files at r2, 1 of 1 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/116)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/116#-:-MS7reLS8-bjFihqV9oL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Pull request merged**
