### PR TITLE
[Readme] Update readme to the pmemkv 1.4 and change snippet to be more generic

### PR DESCRIPTION
**Pull request by KFilipek**
This PR updates pmemkv-java in Maven artifact snippet and changes pmemkv version in README.md.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/165)

### CODE REVIEW

**Comment by KFilipek** [comment]
Changed to always select the latest version, but not lower than 1.0.1.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/165)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[README.md, line 21 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/165#-Mbpt8w91mov15GV1LRg:-Mbpt8w91mov15GV1LRh:bbm0zm5) ([raw file](https://github.com/pmem/pmemkv-java/blob/3fad3cb2b55b7a7666220e9846182c1514533c2e/README.md#L21)):*
> ```Markdown
> 
> * [pmemkv](https://github.com/pmem/pmemkv) - Key-Value Datastore for Persistent Memory
>   * pmemkv source package (pmemkv-devel or libpmemkv-dev)
> ```

since you're updating the readme file, please update min. ver. of pmemkv as well (we've bumped that when merged iterator's PR)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/165)* status: all files reviewed, 5 unresolved discussions (waiting on @KFilipek)

___
*[README.md, line 1 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/165#-MbvHA9S4Up9-oDs7GFH:-MbvHA9S4Up9-oDs7GFI:bccn03m) ([raw file](https://github.com/pmem/pmemkv-java/blob/3fad3cb2b55b7a7666220e9846182c1514533c2e/README.md#L1)):*
> ```Markdown
> [Travis build status](https://travis-ci.org/pmem/pmemkv-java)
> ```

and pls, BTW, remove the Travis shield here ;) we don't use it anymore
___
*[README.md, line 4 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/165#-MbvHueB8qqePWvyTICM:-MbvHueB8qqePWvyTICN:b-1fyyoa) ([raw file](https://github.com/pmem/pmemkv-java/blob/3fad3cb2b55b7a7666220e9846182c1514533c2e/README.md#L4)):*
> ```Markdown
> [GHA build status](https://github.com/pmem/pmemkv-java/actions)
> [PMEMKV-JAVA version](https://github.com/pmem/pmemkv-java/releases/latest)
> ```

and already pls add a new badge:

```
![pmemkv-root maven central](https://maven-badges.herokuapp.com/maven-central/io.pmem/pmemkv-root/badge.svg?style=flat-for-the-badge)
```
___
*[README.md, line 16 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/165#-MbvICzK5isJYYsZ2BUA:-MbvICzK5isJYYsZ2BUB:b-oji8ug) ([raw file](https://github.com/pmem/pmemkv-java/blob/3fad3cb2b55b7a7666220e9846182c1514533c2e/README.md#L16)):*
> ```Markdown
> 
> - [master](https://pmem.io/pmemkv-java/master/html/index.html)
> - [v1.0](https://pmem.io/pmemkv-java/v1.0/html/index.html)
> ```

\+ a link to new docs here, pls
___
*[README.md, line 47 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/165#-MbvIAn37GDCGQtr-m7D:-MbvIAn37GDCGQtr-m7E:b-bfaio2) ([raw file](https://github.com/pmem/pmemkv-java/blob/3fad3cb2b55b7a7666220e9846182c1514533c2e/README.md#L47)):*
> ```Markdown
> 
> Start by installing [pmemkv](https://github.com/pmem/pmemkv/blob/master/INSTALLING.md)
> (currently at least in version **1.0.2**) in your system.
> ```

this is wrong as well ;)

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/165)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[README.md, line 1 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/165#-MbvHA9S4Up9-oDs7GFH:-Mc9Thyp5AcACdiiNKt3:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/3fad3cb2b55b7a7666220e9846182c1514533c2e/README.md#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

and pls, BTW, remove the Travis shield here ;) we don't use it anymore
</blockquote></details>

Done.
___
*[README.md, line 4 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/165#-MbvHueB8qqePWvyTICM:-Mc9Uct521QbT9q9JiKT:b-d54r55) ([raw file](https://github.com/pmem/pmemkv-java/blob/3fad3cb2b55b7a7666220e9846182c1514533c2e/README.md#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

and already pls add a new badge:

```
![pmemkv-root maven central](https://maven-badges.herokuapp.com/maven-central/io.pmem/pmemkv-root/badge.svg?style=flat-for-the-badge)
```
</blockquote></details>

Done. I've extended your code and now should work like a charm
___
*[README.md, line 16 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/165#-MbvICzK5isJYYsZ2BUA:-Mc9WITc7_q_AF6S7glH:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/3fad3cb2b55b7a7666220e9846182c1514533c2e/README.md#L16)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

\+ a link to new docs here, pls
</blockquote></details>

Done.
___
*[README.md, line 21 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/165#-Mbpt8w91mov15GV1LRg:-Mc9_BFS8jnNkUDVPk2B:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/3fad3cb2b55b7a7666220e9846182c1514533c2e/README.md#L21)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

since you're updating the readme file, please update min. ver. of pmemkv as well (we've bumped that when merged iterator's PR)
</blockquote></details>

Done.
___
*[README.md, line 47 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/165#-MbvIAn37GDCGQtr-m7D:-Mc9abm10uqOwvxpVaph:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/3fad3cb2b55b7a7666220e9846182c1514533c2e/README.md#L47)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this is wrong as well ;)
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/165)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-java/165#-Mc9gnRZ53DigqY9pAOX:-Mc9gnRZ53DigqY9pAOY:b-94bzi1) (no related file):*
pls update commit message

---

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/165)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-java/165#-Mc9gnRZ53DigqY9pAOX:-MctNa7d1R6yIcNy81En:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls update commit message
</blockquote></details>

Done.

---

**Pull request merged**
