### PR TITLE
CI update

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
Update CI workflow,
update dependencies installed in the docker image,
bump dependencies versions,
fix auto-doc-update.sh (by installing pmemkv).

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/134)

### CODE REVIEW

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/134#-:-MVRmUv6BTDjnpDwEVj4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/134)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @KFilipek and @lukaszstolarczuk)

___
*[utils/docker/images/prepare-pmemkv.sh, line 25 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/134#-MVVgQjA466Kl4O2pR1G:-MVVgQjBBONJB0r9SuQX:be55kdn) ([raw file](https://github.com/pmem/pmemkv-java/blob/94c843faac19990190fb264480860b816c4ea25b/utils/docker/images/prepare-pmemkv.sh#L25)):*
> ```Shell
> 
> # master: Merge pull request #952 from karczex/dram_cmap_engine; 05.03.2021
> current_pmemkv_version="e135a8c757a8deb9a58d826954780d9eaf1ec5ab"
> ```

You switched commit to one, which adds dram_cmap_engine, but you do not enable the engine in  `prepare_pmemkv`.  Are you do it by purpose?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/134)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @karczex and @KFilipek)

___
*[utils/docker/images/prepare-pmemkv.sh, line 25 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/134#-MVVgQjA466Kl4O2pR1G:-MVVrYNe3-CkG9mwsocq:btmx813) ([raw file](https://github.com/pmem/pmemkv-java/blob/94c843faac19990190fb264480860b816c4ea25b/utils/docker/images/prepare-pmemkv.sh#L25)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

You switched commit to one, which adds dram_cmap_engine, but you do not enable the engine in  `prepare_pmemkv`.  Are you do it by purpose? 
</blockquote></details>

We don't select any specific engines to build here, only use the one enabled by default. And there's no issue I believe, since we only test one or two engines in pmemkv-java, for now.

Maybe we should enable them for more robust testing in here, but that's quite a different topic (various pmemkv versions have various engines available, it won't be trivial to enable in here, for all CI jobs).

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/134#-:-MV_Mf7ZB1L64BWw__EW:bnfp4nl)* status: 4 of 7 files reviewed, all discussions resolved (waiting on @KFilipek)

**Pull request merged**
