### PR TITLE
Improve docker images

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
**note:** If you got better idea/approach for the last commit, please let me know.
I believe, though, proxy settings are enough for now, we rather don't use more than that, aren't we?

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/124)

### CODE REVIEW

**Review by KFilipek — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/124)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by karczex — COMMENTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/124)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[utils/docker/images/Dockerfile.ubuntu-20.04, line 75 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/124#-MTfqAno52YNXmti6DHi:-MTfqAno52YNXmti6DHj:b-18zxv7) ([raw file](https://github.com/pmem/pmemkv-java/blob/ff9207f3c0016f09708036fdab5acedd584282c2/utils/docker/images/Dockerfile.ubuntu-20.04#L75)):*
> ```
> # Setup maven settings
> COPY setup-maven-settings.sh setup-maven-settings.sh
> RUN ./setup-maven-settings.sh
> ```

Proxy configuration should be rather set at image startup (entrypoint).

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/124)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @karczex and @KFilipek)

___
*[utils/docker/images/Dockerfile.ubuntu-20.04, line 75 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/124#-MTfqAno52YNXmti6DHi:-MUgaYzPAbu4t_SjL5B5:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/ff9207f3c0016f09708036fdab5acedd584282c2/utils/docker/images/Dockerfile.ubuntu-20.04#L75)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Proxy configuration should be rather set at image startup (entrypoint). 
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/124#-:-MUgwFtA2ZTHWkLyVSDr:bnfp4nl)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @karczex and @KFilipek)

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/124#-:-MUh81qz9khwc_wtHoXj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

**Pull request merged**
