### PR TITLE
add CI job using maven

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
// CI job execution preview: https://github.com/lukaszstolarczuk/pmemkv-java/runs/2638515771 (see this precise line: [link](https://github.com/lukaszstolarczuk/pmemkv-java/runs/2638515771#step:5:379))

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/153)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/153)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[utils/docker/prepare-for-build.sh, line 50 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/153#-Ma8ZOfvBRODvy2GhvK5:-Ma8ZOfvBRODvy2GhvK6:b-qsi4c4) ([raw file](https://github.com/pmem/pmemkv-java/blob/b0d652328c4a933eb87cf360b9758ea91f43a30d/utils/docker/prepare-for-build.sh#L50)):*
> ```Shell
> 	example_name=${1}
> 	# Find pmemkv package (in the system) and path to example's jar
> 	jar_path=$(find ${HOME}/.m2/repository/io/pmem | grep -E "pmemkv-(root-[0-9.]+).jar$")
> ```

I really don't like this line - does anyone know if we can make it better? I'm not sure if we can somehow skip passing this path to an example's execution...?

**Comment by KFilipek** [comment]
> ```shell
> pmemkv-(root
> ```

We can use example packages with embedded library (e.g. MixedTypesExample-1.0.1-jar-with-dependencies.jar) and it should work like you want

**Review by KFilipek — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/153)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

**Review by karczex — COMMENTED** [review]
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/153)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @KFilipek and @lukaszstolarczuk)

___
*[utils/docker/run-maven-example.sh, line 20 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/153#-MaDFEqx7GBZ_jyfLxxd:-MaDFEqx7GBZ_jyfLxxe:b-jf1xlb) ([raw file](https://github.com/pmem/pmemkv-java/blob/93e4d94486e9040e8ac15a6282d6036d0a817b8d/utils/docker/run-maven-example.sh#L20)):*
> ```Shell
> echo "#############################################################"
> cd ${WORKDIR}
> git apply utils/docker/0001-examples-use-pmemkv-from-maven-repo.patch
> ```

Please don't :) 

I did not tested that, so I cannot promise it will work, but problem from this SO thread seems to be pretty similar to our, and solution in accepted answer is very clean,.  
https://stackoverflow.com/questions/13708738/how-to-get-a-command-line-property-to-overwrite-a-maven-property

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/153)* status: 5 of 10 files reviewed, 1 unresolved discussion (waiting on @karczex and @KFilipek)

___
*[utils/docker/run-maven-example.sh, line 20 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/153#-MaDFEqx7GBZ_jyfLxxd:-MaDXQ-o4QOKrNXFAfE7:b-soywji) ([raw file](https://github.com/pmem/pmemkv-java/blob/93e4d94486e9040e8ac15a6282d6036d0a817b8d/utils/docker/run-maven-example.sh#L20)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Please don't :) 

I did not tested that, so I cannot promise it will work, but problem from this SO thread seems to be pretty similar to our, and solution in accepted answer is very clean,.  
https://stackoverflow.com/questions/13708738/how-to-get-a-command-line-property-to-overwrite-a-maven-property 
</blockquote></details>

OMG, this is waaaay better, thanks!

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/153#-:-MaEw07B4uMOg3uCyolj:bnfp4nl)* status: 5 of 10 files reviewed, all discussions resolved (waiting on @karczex and @KFilipek)

**Pull request merged**
