### PR TITLE
Enable ReadIterator

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
and add example usage of Iterators.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/173)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 7 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/173)* status: 7 of 12 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 220 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/173#-MdMzJqE151tZvnljfHF:-MdMzJqE151tZvnljfHG:b-s1u6py) ([raw file](https://github.com/pmem/pmemkv-java/blob/d4072a83d569cefedc419db629b3a711c0832f6a/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L220)):*
> ```Java
> 
> 		/**
> 		 * Returns value of a record currently pointed by the iterator.
> ```

I think it's quite important to note that any modification done to this value will NOT be reflected in the database. Maybe the return value should be marked as const? (the same for key).
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 421 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/173#-MdMz796AcV_M6jJ2ppf:-MdMz797BO3qLDaO1dIL:b-77reif) ([raw file](https://github.com/pmem/pmemkv-java/blob/d4072a83d569cefedc419db629b3a711c0832f6a/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L421)):*
> ```Java
> 	 * @since 1.2.0
> 	 */
> 	public ReadIterator iterator() throws DatabaseException {
> ```

Hm, I'm not sure about the function name. To be consistent maybe it would be better to have `readIterator`?

**Review by igchor — COMMENTED** [review]
> Reviewed 1 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/173)* status: 8 of 12 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/173)* status: 6 of 12 files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 220 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/173#-MdMzJqE151tZvnljfHF:-MdNCzSlAcw_0BrZyjiZ:bbwml61) ([raw file](https://github.com/pmem/pmemkv-java/blob/d4072a83d569cefedc419db629b3a711c0832f6a/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L220)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think it's quite important to note that any modification done to this value will NOT be reflected in the database. Maybe the return value should be marked as const? (the same for key).
</blockquote></details>

Done.
I'm not sure if we can make the returned value const in Java...?
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 421 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/173#-MdMz796AcV_M6jJ2ppf:-MdN6oyA6CS8aqflDXfE:b6clzn5) ([raw file](https://github.com/pmem/pmemkv-java/blob/d4072a83d569cefedc419db629b3a711c0832f6a/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L421)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, I'm not sure about the function name. To be consistent maybe it would be better to have `readIterator`? 
</blockquote></details>

I've chosen this name based on C API, but I agree, it's better to name this readIter.
Done.

**Review by KFilipek — COMMENTED** [review]
> Reviewed 3 of 12 files at r1, 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/173)* status: 9 of 12 files reviewed, 3 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[examples/IteratorExample/src/main/java/IteratorExample.java, line 5 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/173#-MdNO0Q2DddPo3h97X6-:-MdNO0Q37RayVb4YFQRO:ba3hwyx) ([raw file](https://github.com/pmem/pmemkv-java/blob/7a19caffd8e19c0b84f15d7638918b3b79963e37/examples/IteratorExample/src/main/java/IteratorExample.java#L5)):*
> ```Java
> 
> import io.pmem.pmemkv.Database;
> import io.pmem.pmemkv.Converter;
> ```

Invert order
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 220 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/173#-MdMzJqE151tZvnljfHF:-MdNOm5dC6_8JQJzwTvY:b7kv7ws) ([raw file](https://github.com/pmem/pmemkv-java/blob/d4072a83d569cefedc419db629b3a711c0832f6a/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L220)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Done.
I'm not sure if we can make the returned value const in Java...?
</blockquote></details>

No, function can return by value or reference. You can change behaviour only by changing behaviour of accessors to protect from modifications or returning value/copy of on object. 
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseIteratorTest.java, line 16 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/173#-MdNRZ8tEc3JgbaFDTKN:-MdNRZ8tEc3JgbaFDTKO:b5p818k) ([raw file](https://github.com/pmem/pmemkv-java/blob/7a19caffd8e19c0b84f15d7638918b3b79963e37/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseIteratorTest.java#L16)):*
> ```Java
> import static org.junit.Assert.*;
> 
> public class DatabaseIteratorTest {
> ```

DatabaseReadIterator. DatabaseIterator can be two-way version of iterator looking from the name

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/173)* status: 9 of 12 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 220 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/173#-MdMzJqE151tZvnljfHF:-MdRLjs39PM4Xs7AlMhN:bun63vs) ([raw file](https://github.com/pmem/pmemkv-java/blob/d4072a83d569cefedc419db629b3a711c0832f6a/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L220)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

No, function can return by value or reference. You can change behaviour only by changing behaviour of accessors to protect from modifications or returning value/copy of on object. 
</blockquote></details>

Maybe it would be simpler to just say the return value is a copy of the element? (because it is, right?)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/173)* status: 9 of 12 files reviewed, 2 unresolved discussions (waiting on @KFilipek)

___
*[examples/IteratorExample/src/main/java/IteratorExample.java, line 5 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/173#-MdNO0Q2DddPo3h97X6-:-MdRY63w0yufHuBg0nmy:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/7a19caffd8e19c0b84f15d7638918b3b79963e37/examples/IteratorExample/src/main/java/IteratorExample.java#L5)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Invert order
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 220 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/173#-MdMzJqE151tZvnljfHF:-MdRYjOJ6LIEyF1Lr9BZ:b-rsomo6) ([raw file](https://github.com/pmem/pmemkv-java/blob/d4072a83d569cefedc419db629b3a711c0832f6a/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L220)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Maybe it would be simpler to just say the return value is a copy of the element? (because it is, right?)
</blockquote></details>

it's a copy of the DB record, but in Java you always return by reference (unless it's primitive type).

I've re-phrased it a little, again.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseIteratorTest.java, line 16 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/173#-MdNRZ8tEc3JgbaFDTKN:-MdRZOwE0BQqW3mSKmj3:bb5xzow) ([raw file](https://github.com/pmem/pmemkv-java/blob/7a19caffd8e19c0b84f15d7638918b3b79963e37/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseIteratorTest.java#L16)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

DatabaseReadIterator. DatabaseIterator can be two-way version of iterator looking from the name
</blockquote></details>

it's just a name of the test suite - I believe we may extend it with more tests (for write iterator), when the time comes

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/173)* status: 7 of 12 files reviewed, 5 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[examples/IteratorExample/src/main/java/IteratorExample.java, line 27 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/173#-MdRRsUXAkWUhHGfbJVQ:-MdRRsUY1sepyq7RF_42:bej838m) ([raw file](https://github.com/pmem/pmemkv-java/blob/7a19caffd8e19c0b84f15d7638918b3b79963e37/examples/IteratorExample/src/main/java/IteratorExample.java#L27)):*
> ```Java
> public class IteratorExample {
> 	public static void main(String[] args) {
> 		String ENGINE = "vsmap";
> ```

nit: You may add some comment, how choice of engine affects seek* methods 
___
*[jni-binding/io_pmem_pmemkv_Database_ReadIterator.cpp, line 176 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/173#-MdRZRoH52n2JOryWFlJ:-MdRZRoH52n2JOryWFlK:b19ijjd) ([raw file](https://github.com/pmem/pmemkv-java/blob/7a19caffd8e19c0b84f15d7638918b3b79963e37/jni-binding/io_pmem_pmemkv_Database_ReadIterator.cpp#L176)):*
> ```cpp
>     auto key_jbuffer = env->NewDirectByteBuffer(const_cast<char*>(key.data()), key.size());
>     if (env->ExceptionCheck() == JNI_TRUE)
>         return nullptr;  // Propagate exception
> ```

NewDirectByteBuffer returns NULL if an exception occurs, or if JNI access to direct buffers is not supported by this virtual machine. 
https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/functions.html#NewDirectByteBuffer
So you do not need this ExceptionCheck() and may just return key_jbuffer, as it was before. 
Do you encounter any problems with previous implementation?
___
*[jni-binding/io_pmem_pmemkv_Database_ReadIterator.cpp, line 191 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/173#-MdR_Lur7o8kygzyaJeD:-MdR_LusAlwktL_qDeWA:b-cozsat) ([raw file](https://github.com/pmem/pmemkv-java/blob/56ae87d687dae0d8269a1c4f36cb152e44f23dc0/jni-binding/io_pmem_pmemkv_Database_ReadIterator.cpp#L191)):*
> ```cpp
> JNIEXPORT jobject JNICALL Java_io_pmem_pmemkv_Database_00024ReadIterator_iterator_1value
>   (JNIEnv *env, jobject, jlong ptr) {
>   auto r_it = reinterpret_cast<pmem::kv::db::read_iterator*>(ptr);
> ```

nit:
in fact this code also may be moved to boilerplate method, like the seek.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/173)* status: 6 of 12 files reviewed, 3 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[examples/IteratorExample/src/main/java/IteratorExample.java, line 27 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/173#-MdRRsUXAkWUhHGfbJVQ:-MdRzlr-CXiJxpF_9E92:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/7a19caffd8e19c0b84f15d7638918b3b79963e37/examples/IteratorExample/src/main/java/IteratorExample.java#L27)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

nit: You may add some comment, how choice of engine affects seek* methods 
</blockquote></details>

Done.
___
*[jni-binding/io_pmem_pmemkv_Database_ReadIterator.cpp, line 176 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/173#-MdRZRoH52n2JOryWFlJ:-MdRzsaa4RO0NP3BXftN:bq7pllo) ([raw file](https://github.com/pmem/pmemkv-java/blob/7a19caffd8e19c0b84f15d7638918b3b79963e37/jni-binding/io_pmem_pmemkv_Database_ReadIterator.cpp#L176)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

NewDirectByteBuffer returns NULL if an exception occurs, or if JNI access to direct buffers is not supported by this virtual machine. 
https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/functions.html#NewDirectByteBuffer
So you do not need this ExceptionCheck() and may just return key_jbuffer, as it was before. 
Do you encounter any problems with previous implementation?
</blockquote></details>

I believe we need this check to avoid returning nullptr and then crash key() / value() method in Java (in a call to Converter).
This way we get an exception in Java and a user can/should handle it with their own code.
___
*[jni-binding/io_pmem_pmemkv_Database_ReadIterator.cpp, line 191 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/173#-MdR_Lur7o8kygzyaJeD:-MdS-FJE48YKz92YzUxH:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/56ae87d687dae0d8269a1c4f36cb152e44f23dc0/jni-binding/io_pmem_pmemkv_Database_ReadIterator.cpp#L191)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

nit:
in fact this code also may be moved to boilerplate method, like the seek.
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/173#-:-MdS7KMo7o2lmRaol-py:bnfp4nl)* status: 6 of 12 files reviewed, 3 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/173#-:-MdSBOUc3pP1YdZ7LEpw:bnfp4nl)* status: 6 of 12 files reviewed, 1 unresolved discussion (waiting on @igchor, @karczex, and @KFilipek)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 220 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/173#-MdMzJqE151tZvnljfHF:-MdSB8c500cNlyR7_Bg5:b-81la7d) ([raw file](https://github.com/pmem/pmemkv-java/blob/d4072a83d569cefedc419db629b3a711c0832f6a/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L220)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it's a copy of the DB record, but in Java you always return by reference (unless it's primitive type).

I've re-phrased it a little, again.
</blockquote></details>

Right

**Pull request merged**
