### PR TITLE
PicturesExample: small refactor

### PR DESCRIPTION
**Pull request by KFilipek**
- remove dummy code
- add 'Override' annotation where is needed
- move example logic to dedicated class

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/118)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
please rebase to stable-1.0

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/118#-:-MRyJD549DG7WrPAD0eU:b-ihvrl1)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[examples/PicturesExample/src/main/java/PicturesExample.java, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/118#-MRyJFRFBB9DdeF9VplP:-MRyJFRFBB9DdeF9VplQ:b-8mxykb) ([raw file](https://github.com/pmem/pmemkv-java/blob/f063a1f84395c6fdf52fd1726e62b85e0ee8d442/examples/PicturesExample/src/main/java/PicturesExample.java#L2)):*
> ```Java
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2020, Intel Corporation */
> ```

-2021

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/118)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[examples/PicturesExample/src/main/java/PicturesExample.java, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/118#-MRyJFRFBB9DdeF9VplP:-MRyLr4WDnhDNkv0jY2K:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/f063a1f84395c6fdf52fd1726e62b85e0ee8d442/examples/PicturesExample/src/main/java/PicturesExample.java#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

-2021
</blockquote></details>

Done.

**Comment by KFilipek** [comment]
I've also reordered the imports

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/118)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @KFilipek)

___
*[examples/PicturesExample/src/main/java/PicturesExample.java, line 125 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/118#-MRyUU7E2nUe3oWuwnZ_:-MRyUU7G0c_y7VTs-Xdu:bbjum3m) ([raw file](https://github.com/pmem/pmemkv-java/blob/a1a20085499d55a5dfaa4575581a1e742766ed1a/examples/PicturesExample/src/main/java/PicturesExample.java#L125)):*
> ```Java
> 		AtomicInteger yPosition = new AtomicInteger(0);
> 		db.getAll((k, v) -> {
> 			System.out.println("\tDraw" + k);
> ```

pls make it `"\tDraw " + k` (add a space)
___
*[examples/PicturesExample/src/main/java/PicturesExample.java, line 152 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/118#-MRyUnyPE9RUfsqco-GC:-MRyUnyPE9RUfsqco-GD:b-bemg2i) ([raw file](https://github.com/pmem/pmemkv-java/blob/a1a20085499d55a5dfaa4575581a1e742766ed1a/examples/PicturesExample/src/main/java/PicturesExample.java#L152)):*
> ```Java
> 
> 		System.out.println("Parameters:");
> 		System.out.println("InputDir" + inputDirEnv);
> ```

rebase went wrong, I've changed this line ;) (`"InputDir: " + ...`)
___
*[examples/PicturesExample/src/main/java/PicturesExample.java, line 157 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/118#-MRyWZO88UDi_ZHLLA7G:-MRyWZO88UDi_ZHLLA7H:br8p9g3) ([raw file](https://github.com/pmem/pmemkv-java/blob/a1a20085499d55a5dfaa4575581a1e742766ed1a/examples/PicturesExample/src/main/java/PicturesExample.java#L157)):*
> ```Java
> 
> 		PmemkvPicture m = null;
> 		if (pmemkvPathEnv != null) {
> ```

this can't be null, you just checked this few lines above. Did you mean to check here for Size?

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/118)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[examples/PicturesExample/src/main/java/PicturesExample.java, line 125 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/118#-MRyUU7E2nUe3oWuwnZ_:-MRycqr76j7_wlsgAGxj:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/a1a20085499d55a5dfaa4575581a1e742766ed1a/examples/PicturesExample/src/main/java/PicturesExample.java#L125)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls make it `"\tDraw " + k` (add a space)
</blockquote></details>

Done.
___
*[examples/PicturesExample/src/main/java/PicturesExample.java, line 152 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/118#-MRyUnyPE9RUfsqco-GC:-MRycWm7Da8D8XwRE7Jj:b8g159s) ([raw file](https://github.com/pmem/pmemkv-java/blob/a1a20085499d55a5dfaa4575581a1e742766ed1a/examples/PicturesExample/src/main/java/PicturesExample.java#L152)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

rebase went wrong, I've changed this line ;) (`"InputDir: " + ...`)
</blockquote></details>

Done. Indeed.
___
*[examples/PicturesExample/src/main/java/PicturesExample.java, line 157 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/118#-MRyWZO88UDi_ZHLLA7G:-MRycnUNC51EZzcShCUw:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/a1a20085499d55a5dfaa4575581a1e742766ed1a/examples/PicturesExample/src/main/java/PicturesExample.java#L157)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this can't be null, you just checked this few lines above. Did you mean to check here for Size?
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/118)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[examples/PicturesExample/src/main/java/PicturesExample.java, line 79 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/118#-MRyg1_A-oQ2-MKabWtD:-MRyg1_A-oQ2-MKabWtE:b-by00ky) ([raw file](https://github.com/pmem/pmemkv-java/blob/12753c29cdfde5ee03caba965a53d7dd678fc544/examples/PicturesExample/src/main/java/PicturesExample.java#L79)):*
> ```Java
> }
> 
> /* Add Pmemkv superpowers to the Canvas classs */
> ```

I can see snaky classsss ;)

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/118)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[examples/PicturesExample/src/main/java/PicturesExample.java, line 79 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/118#-MRyg1_A-oQ2-MKabWtD:-MRyhzVCE-yaAl59tId8:bb48e41) ([raw file](https://github.com/pmem/pmemkv-java/blob/12753c29cdfde5ee03caba965a53d7dd678fc544/examples/PicturesExample/src/main/java/PicturesExample.java#L79)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I can see snaky classsss ;)
</blockquote></details>

Done. Sasasasa

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/118#-:-MRykpVSB_8vArNN08Ae:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/118#-:-MRzJ882A3mcvHLgs5jn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)

**Pull request merged**
