### PR TITLE
enable specifying config params from JSON Object

### LINKED ISSUE #161: FEAT: Extend Builder with fromJson() method
FEAT: Extend Builder with fromJson() method

## Rationale

Such method would be useful for applications like YCSB where we would like to test different configurations. Right now, testing eg. with different pool size would require changes in YCSB code.

## API Changes

New Builder.fromJson(...) method

## Implementation details

Use pmemkv_config_from_json or native Java code.

## Other

Add support for YCSB driver.

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
given as String or InputStream.

Fixes #161

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/171)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 5 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/171)* status: 5 of 10 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[jni-binding/io_pmem_pmemkv_Database_Builder.cpp, line 50 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/171#-McDw1DdA-6igpE6gfew:-McDw1DdA-6igpE6gfex:b-5dtbik) ([raw file](https://github.com/pmem/pmemkv-java/blob/62ce3747ecfcec0fdfe82d67146947e61e5b457d/jni-binding/io_pmem_pmemkv_Database_Builder.cpp#L50)):*
> ```cpp
> extern "C" JNIEXPORT void JNICALL Java_io_pmem_pmemkv_Database_00024Builder_config_1from_1json
>   (JNIEnv *env, jobject, jlong cfg, jstring jjson) {
>     const char* cjson = env->GetStringUTFChars(jjson, NULL);
> ```

can this fail?
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 722 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/171#-McDxSQBBf52FIUMDlOp:-McDxSQC65YjUFmHpBjp:b-yh0jo) ([raw file](https://github.com/pmem/pmemkv-java/blob/62ce3747ecfcec0fdfe82d67146947e61e5b457d/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L722)):*
> ```Java
> 			try (Scanner scanner = new Scanner(jsonStream, UTF_8.name())) {
> 				/*
> 				 * sets delimiter to the beginning of the input, so it reads the whole content
> ```

 why set to the beginning and not to the end?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/171)* status: 5 of 10 files reviewed, 3 unresolved discussions (waiting on @igchor)

___
*[jni-binding/io_pmem_pmemkv_Database_Builder.cpp, line 50 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/171#-McDw1DdA-6igpE6gfew:-McEB3LCB-9MloNmbG_7:b5p5at1) ([raw file](https://github.com/pmem/pmemkv-java/blob/62ce3747ecfcec0fdfe82d67146947e61e5b457d/jni-binding/io_pmem_pmemkv_Database_Builder.cpp#L50)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

can this fail?
</blockquote></details>

according to docs it should not throw anything if that what you were asking... but it may return NULL if failed.

Do we want to take care of checking the null before passing it to pmemkv...?
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 718 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/171#-McEBXbp1PBVd7vidr32:-McEBXbp1PBVd7vidr33:blc7w0l) ([raw file](https://github.com/pmem/pmemkv-java/blob/62ce3747ecfcec0fdfe82d67146947e61e5b457d/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L718)):*
> ```Java
> 		 * @since 1.2.0
> 		 */
> 		public Builder<K, V> fromJson(InputStream jsonStream) throws BuilderException {
> ```

actually - the question is - do we want to keep this overload, at all? A user could specify their own way of converting a Stream into a String and would choose their favorite encoding (here we're enforcing UTF_8)...
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 722 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/171#-McDxSQBBf52FIUMDlOp:-McEBM5i0zIrVbH4lkCb:bsihsiv) ([raw file](https://github.com/pmem/pmemkv-java/blob/62ce3747ecfcec0fdfe82d67146947e61e5b457d/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L722)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

 why set to the beginning and not to the end?
</blockquote></details>

as far as I understand it, it behaves the same in our case - either we can use "\A" or "\Z" az delimiter and it will just read the whole content of the Stream.

**Review by karczex — COMMENTED** [review]
Did you test your change against this bug in pmemkv?  https://github.com/pmem/pmemkv/issues/568 
In pmemkv-python we enforce config to be dictionary, so it's very hard to pass malformed input.
 https://github.com/pmem/pmemkv-python/blob/094bc84fdabff81c2eb2017d32caad2582835f90/pmemkv/pmemkv.py#L69 

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/171#-:-McIg8OtEj8OEKhFWtU1:b3sa9jo)* status: 5 of 10 files reviewed, 6 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[ChangeLog, line 8 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/171#-McIdGLcExnI5b6Vbtol:-McIdGLcExnI5b6Vbtom:bypfmri) ([raw file](https://github.com/pmem/pmemkv-java/blob/62ce3747ecfcec0fdfe82d67146947e61e5b457d/ChangeLog#L8)):*
> ```
> 	-
> 
> 	Minor changes:
> ```

It's API extension, so don't be so shy, and move it to Improvements :) 
___
*[jni-binding/io_pmem_pmemkv_Database_Builder.cpp, line 50 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/171#-McDw1DdA-6igpE6gfew:-McIsrE8-o3VbIo8kjwZ:b58pzf4) ([raw file](https://github.com/pmem/pmemkv-java/blob/62ce3747ecfcec0fdfe82d67146947e61e5b457d/jni-binding/io_pmem_pmemkv_Database_Builder.cpp#L50)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

according to docs it should not throw anything if that what you were asking... but it may return NULL if failed.

Do we want to take care of checking the null before passing it to pmemkv...?
</blockquote></details>

We may validate json in java layer....
In pmemkv_config_form_json we do assert so passing null will cause application abort, which is probably now what we want here. 
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 692 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/171#-McIr3Qa-cyElwceoS2M:-McIr3Qa-cyElwceoS2N:bfn9xwf) ([raw file](https://github.com/pmem/pmemkv-java/blob/62ce3747ecfcec0fdfe82d67146947e61e5b457d/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L692)):*
> ```Java
> 		 * Reads config parameters from JSON Object stored in a string. One by one, each
> 		 * parameter is inserted into config. It can be used alternatively with
> 		 * setPath/setSize/etc., but it will fail if defining the same parameter twice.
> ```

Probably need to specify, what happens when you use both fromJson and set* at the same time. I may imagine scenario, where user (for some tricky and ugly reason) wants to compute size, but pass path via json.  
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 702 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/171#-McIpxFH4JtH4fMogD-n:-McIpxFIDh0w_UId9H9Z:b-givmft) ([raw file](https://github.com/pmem/pmemkv-java/blob/62ce3747ecfcec0fdfe82d67146947e61e5b457d/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L702)):*
> ```Java
> 		 */
> 		public Builder<K, V> fromJson(String json) throws BuilderException {
> 			config_from_json(config, json);
> ```

... Json early validation may be done here. 
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 718 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/171#-McEBXbp1PBVd7vidr32:-McIlcSPDkYN1ozz-UuZ:b-u1v0u2) ([raw file](https://github.com/pmem/pmemkv-java/blob/62ce3747ecfcec0fdfe82d67146947e61e5b457d/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L718)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

actually - the question is - do we want to keep this overload, at all? A user could specify their own way of converting a Stream into a String and would choose their favorite encoding (here we're enforcing UTF_8)...
</blockquote></details>

IMO, This overload is needed, due to it's flexibility.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/171)* status: 5 of 10 files reviewed, 6 unresolved discussions (waiting on @igchor and @karczex)

___
*[ChangeLog, line 8 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/171#-McIdGLcExnI5b6Vbtol:-McJ4W323j75pwiZWlnH:beqefbv) ([raw file](https://github.com/pmem/pmemkv-java/blob/62ce3747ecfcec0fdfe82d67146947e61e5b457d/ChangeLog#L8)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

It's API extension, so don't be so shy, and move it to Improvements :) 
</blockquote></details>

:smile: 
done.
___
*[jni-binding/io_pmem_pmemkv_Database_Builder.cpp, line 50 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/171#-McDw1DdA-6igpE6gfew:-McJfz0I44JXv0xjat0I:b-yh10tr) ([raw file](https://github.com/pmem/pmemkv-java/blob/62ce3747ecfcec0fdfe82d67146947e61e5b457d/jni-binding/io_pmem_pmemkv_Database_Builder.cpp#L50)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

We may validate json in java layer....
In pmemkv_config_form_json we do assert so passing null will cause application abort, which is probably now what we want here. 
</blockquote></details>

Done. Good catch
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 692 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/171#-McIr3Qa-cyElwceoS2M:-McJ6S8q3V6C_SuE7nNx:bpu4k6q) ([raw file](https://github.com/pmem/pmemkv-java/blob/62ce3747ecfcec0fdfe82d67146947e61e5b457d/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L692)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Probably need to specify, what happens when you use both fromJson and set* at the same time. I may imagine scenario, where user (for some tricky and ugly reason) wants to compute size, but pass path via json.  
</blockquote></details>

I thought this was clear with my description - you can just do this, as long as you don't overlap the same params.

I've added a test for that case and fix this description a little.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 702 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/171#-McIpxFH4JtH4fMogD-n:-McJg0bI9mEobGbm-ga3:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/62ce3747ecfcec0fdfe82d67146947e61e5b457d/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L702)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

... Json early validation may be done here. 
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 718 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/171#-McEBXbp1PBVd7vidr32:-McJ7GRaC_sGF2DLOwzI:b-9pc2in) ([raw file](https://github.com/pmem/pmemkv-java/blob/62ce3747ecfcec0fdfe82d67146947e61e5b457d/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L718)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

IMO, This overload is needed, due to it's flexibility.
</blockquote></details>

but a user could do the same 3 lines I did, in their own code... ;)
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 722 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/171#-McDxSQBBf52FIUMDlOp:-McJgXFy6gTVyLxJucPH:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/62ce3747ecfcec0fdfe82d67146947e61e5b457d/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L722)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

as far as I understand it, it behaves the same in our case - either we can use "\A" or "\Z" az delimiter and it will just read the whole content of the Stream.
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/171)* status: 8 of 11 files reviewed, 10 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[README.md, line 47 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/171#-McE8O3635JviNS0OLMS:-McK7xqKCQQWLjRboDZf:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/62ce3747ecfcec0fdfe82d67146947e61e5b457d/README.md#L47)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> json
> ```
JSON
It's an acronym.
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 11 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/171#-McE9e1X7iXaI7oPt3c8:-McK8D-61GM8zhdsV9u7:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/62ce3747ecfcec0fdfe82d67146947e61e5b457d/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L11)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

move it to the second import block
</blockquote></details>

Done.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseTest.java, line 12 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/171#-McJos_jDItBTz_0kSpc:-McK8zwF2WDejpcr4uW6:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/d71b6e092f5235e44da20581fd594143b2899541/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseTest.java#L12)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

We should avoid using wildcard imports, especially in this scope.
</blockquote></details>

Done.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseTest.java, line 14 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/171#-McJorJy9O8saQm2iXg7:-McK8zop121ZMjD1kozJ:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/d71b6e092f5235e44da20581fd594143b2899541/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseTest.java#L14)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/171)* status: 8 of 11 files reviewed, 7 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 718 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/171#-McEBXbp1PBVd7vidr32:-McrqBYb9bXIz71ELlY0:b-w8i71a) ([raw file](https://github.com/pmem/pmemkv-java/blob/62ce3747ecfcec0fdfe82d67146947e61e5b457d/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L718)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

but a user could do the same 3 lines I did, in their own code... ;)
</blockquote></details>

That's a good point. 
Another idea: As we now depend on JSONobject  anyway, maybe we may add overload for JSONobject instead of InputStrem?

**Review by KFilipek — COMMENTED** [review]
:lgtm: from my side

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/171#-:-Mcs6SwdB5y0dLc1UtP-:b-1ht3y4)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
I've dropped support for JSON preliminary parsing, for now. We need to figure out the proper way of adding external dependencies for our project.

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/171#-:-MdHO0qy8mREHqoqO2T9:bf2h74)* status: 6 of 11 files reviewed, 3 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/171#-:-MdI3OQ8EY5pcBhHMshv:bnfp4nl)* status: 4 of 11 files reviewed, 1 unresolved discussion (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/171#-:-MdM3nKS8DjAXOFYM22W:bnfp4nl)* status: 4 of 11 files reviewed, 1 unresolved discussion (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

**Pull request merged**
