### PR TITLE
[tests] add testcase for builder destruction

### PR DESCRIPTION
**Pull request by KFilipek**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/129)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/129)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java, line 87 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/129#-MUDPyj98ClrnkPnXWeg:-MUDPyj98ClrnkPnXWeh:bpbhnxa) ([raw file](https://github.com/pmem/pmemkv-java/blob/76508a77689ef9a62f8973464267aedf6c385cd1/pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java#L87)):*
> ```Java
> 		boolean startError = false;
> 		try {
> 			db = new Database.Builder<ByteBuffer, ByteBuffer>(ENGINE)
> ```

can't you use the functions createDB and openDB?

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/129)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @igchor and @KFilipek)

___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java, line 87 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/129#-MUDPyj98ClrnkPnXWeg:-MUEX0e9BIxDN0-0P_d7:b-6py5i1) ([raw file](https://github.com/pmem/pmemkv-java/blob/76508a77689ef9a62f8973464267aedf6c385cd1/pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java#L87)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

can't you use the functions createDB and openDB?
</blockquote></details>

Sure, but my intention was to run in one scope to trigger GC when function finish like in YCSB code

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/129)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/129#-MUJ5f8XDyfXDULIJ6mj:-MUJ5f8XDyfXDULIJ6mk:b-8mxykb) ([raw file](https://github.com/pmem/pmemkv-java/blob/76508a77689ef9a62f8973464267aedf6c385cd1/pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java#L2)):*
> ```Java
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2020, Intel Corporation */
> ```

-2021
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java, line 81 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/129#-MUJ5XEI8nmBG7tuYsT5:-MUJ5XEJ4MPs-Pj9BlrK:bm4yhch) ([raw file](https://github.com/pmem/pmemkv-java/blob/76508a77689ef9a62f8973464267aedf6c385cd1/pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java#L81)):*
> ```Java
> 
> 	@Test
> 	public void testConfigRelease() {
> ```

can you please add a short description of this test

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/129)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/129#-MUJ5f8XDyfXDULIJ6mj:-MUJCL7lEnNVJ2kRwhVg:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/76508a77689ef9a62f8973464267aedf6c385cd1/pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

-2021
</blockquote></details>

Done.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java, line 81 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/129#-MUJ5XEI8nmBG7tuYsT5:-MUJCLyo73eZEczkQGAm:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/76508a77689ef9a62f8973464267aedf6c385cd1/pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java#L81)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

can you please add a short description of this test
</blockquote></details>

Done.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java, line 87 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/129#-MUDPyj98ClrnkPnXWeg:-MUJCMbBBKiWd_tIlDbR:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/76508a77689ef9a62f8973464267aedf6c385cd1/pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java#L87)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Sure, but my intention was to run in one scope to trigger GC when function finish like in YCSB code
</blockquote></details>

Done.

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/129)* status: all files reviewed, 3 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java, line 87 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/129#-MUDPyj98ClrnkPnXWeg:-MUNbZpz0DsddcsAp8FL:bnsyi2l) ([raw file](https://github.com/pmem/pmemkv-java/blob/76508a77689ef9a62f8973464267aedf6c385cd1/pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java#L87)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Does it matter? I don't think GC is called when the object goes out of scope - but rather at some arbitrary moment - isn't that right?
(BTW, those the builder objects, which I think are the cause of the problem, are not in the same scope anyway)

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/129#-:-MVVdlaH61oBW0ky27Mv:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

**Comment by KFilipek** [comment]
> > _[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/129)_ status: all files reviewed, 3 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)
> 
> _[pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java, line 87 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/129#-MUDPyj98ClrnkPnXWeg:-MUNbZpz0DsddcsAp8FL:bnsyi2l) ([raw file](https://github.com/pmem/pmemkv-java/blob/76508a77689ef9a62f8973464267aedf6c385cd1/pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java#L87)):_
> Previously, KFilipek (Krzysztof Filipek) wrote…
> 
> Does it matter? I don't think GC is called when the object goes out of scope - but rather at some arbitrary moment - isn't that right?
> (BTW, those the builder objects, which I think are the cause of the problem, are not in the same scope anyway)

"Any exception thrown by the finalize method causes the finalization of this object to be halted, but is otherwise ignored."
So, if you have ObjectStream that derives by Stream class, then if your ObjectStream will be GC finalize should be called, if exception will be thrown, then Stream finalize will never be invoked. This idiom guarantees that this base class finalize will be invoked and exception ignored.

**Comment by KFilipek** [comment]
I believe this PR is outdated after some changes, especially after finalize fix.

**Pull request closed without merging**
