### PR TITLE
tests: make test path configurable by maven property

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
fixes: #88

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/148)

### CODE REVIEW

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/148#-:-MYyE6LR8S3hXbXUYPmj:bnfp4nl)* status: 2 of 6 files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/148#-:-MYyKCHg9vevw2izFsL-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Comment by lukaszstolarczuk** [comment]
I've browse through my changes and I've seen some minor tweaks to apply - so, it's updated a bit yet.

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/148#-:-MYyzvbE3fj6DasQIjLo:bnfp4nl)* status: 2 of 6 files reviewed, all discussions resolved (waiting on @KFilipek)

**Pull request merged**
