### PR TITLE
[java part] add throws clause for methods

### PR DESCRIPTION
**Pull request by KFilipek**
Add throws clause for proper documentation generation and also for user information about possible exception

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/109)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/109)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-java/109#-MRZRkNt9yLUws80S_rU:-MRZRkNt9yLUws80S_rV:bw8o1zw) (no related file):*
just a quick question - in commit msg you say "for methods" - I can only see one, is it just a misspell or you forgot to commit something?

---

**Comment by KFilipek** [comment]
> > Reviewed 1 of 1 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/109)_ status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)
> 
> _[a discussion](https://reviewable.io/reviews/pmem/pmemkv-java/109#-MRZRkNt9yLUws80S_rU:-MRZRkNt9yLUws80S_rV:bw8o1zw) (no related file):_
> just a quick question - in commit msg you say "for methods" - I can only see one, is it just a misspell or you forgot to commit something?

My intention was to discuss the way we can resolve documentation and exception issue at once.

**Review by igchor — APPROVED** [review]
:lgtm: just update the license

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/109#-:-MT4rB2D-65X6dHRe8mc:b-ppecww)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 2 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/109#-MT4r5liA9UJ8PpRFH8p:-MT4r5liA9UJ8PpRFH8q:b-4prc1g) ([raw file](https://github.com/pmem/pmemkv-java/blob/9e7ac30dd52198616c1c83e1577a46483c2afd80/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L2)):*
> ```Java
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2017-2020, Intel Corporation */
> ```

please update the license

**Review by igchor — COMMENTED** [review]
Also, please make this PR to stable

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/109#-:-MT4rJH44JHA2V2cZlTP:b-bcis8o)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/109)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 518 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/109#-MT58gnN2aZEvPa7GTvW:-MT58gnN2aZEvPa7GTvX:bh9a7v5) ([raw file](https://github.com/pmem/pmemkv-java/blob/9e7ac30dd52198616c1c83e1577a46483c2afd80/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L518)):*
> ```Java
> 		}
> 
> 		// JNI DATABASE BUILDER METHODS
> ```

not everything below this line is a jni builder methods

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/109)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 2 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/109#-MT4r5liA9UJ8PpRFH8p:-MT5GOg43LiHVloeeU8F:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/9e7ac30dd52198616c1c83e1577a46483c2afd80/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L2)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

please update the license
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 518 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/109#-MT58gnN2aZEvPa7GTvW:-MT5GPwo7QfZmSzXzSmz:b-l8yvir) ([raw file](https://github.com/pmem/pmemkv-java/blob/9e7ac30dd52198616c1c83e1577a46483c2afd80/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L518)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

not everything below this line is a jni builder methods
</blockquote></details>

Done. Moved up.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/109#-:-MT5JW9Z4PUbImfK8jDT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

**Pull request merged**
