### PR TITLE
refactor: cleanup unused variables and imports

### PR DESCRIPTION
**Pull request by KFilipek**
I will also look at the reflection mechanism to extend test: exceptionsHierarchy()

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/122)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/122)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/122#-MT563vL2Wl3Bi0kI4A_:-MT563vL2Wl3Bi0kI4Aa:b-o4zyit) ([raw file](https://github.com/pmem/pmemkv-java/blob/edfd3ee2f513b4cbcfa1e6da7ec5402b112b2b1c/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L2)):*
> ```Java
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2017-2020, Intel Corporation */
> ```

2021 (all files)
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java, line 36 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/122#-MT57kXx4Vcv3zDqA-Ql:-MT57kXy9Ta6KtIER_7l:b-b6s4a4) ([raw file](https://github.com/pmem/pmemkv-java/blob/278ad9a67314589638913616d03e726c1cbeecc0/pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java#L36)):*
> ```Java
> 	private Database<ByteBuffer, ByteBuffer> buildDB(String engine) {
> 		return new Database.Builder<ByteBuffer, ByteBuffer>(engine)
> 				.setSize(1073741824)
> ```

why removed the break line? I believe it was more readable

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/122)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/122#-MT563vL2Wl3Bi0kI4A_:-MT5CkhvAk15HEcBNmLu:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/edfd3ee2f513b4cbcfa1e6da7ec5402b112b2b1c/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

2021 (all files)
</blockquote></details>

Done.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java, line 36 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/122#-MT57kXx4Vcv3zDqA-Ql:-MT5CmsM3xGH_1unPM6r:b-id9fwi) ([raw file](https://github.com/pmem/pmemkv-java/blob/278ad9a67314589638913616d03e726c1cbeecc0/pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java#L36)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why removed the break line? I believe it was more readable
</blockquote></details>

Format forced me, but I tried to negotiate with him

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/122)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java, line 68 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/122#-MT5JqAyAYILkQ_CnWJe:-MT5JqAyAYILkQ_CnWJf:b-onalzq) ([raw file](https://github.com/pmem/pmemkv-java/blob/278ad9a67314589638913616d03e726c1cbeecc0/pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java#L68)):*
> ```Java
> 		try {
> 			db = new Database.Builder<ByteBuffer, ByteBuffer>(ENGINE)
> 					.setSize(1073741824)
> ```

there's still few more of these line breaks (see here and below in the review)

**Review by igchor — APPROVED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/122)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/122)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)

___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java, line 68 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/122#-MT5JqAyAYILkQ_CnWJe:-MT5eqsdA2XAnKgvWNJ6:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/278ad9a67314589638913616d03e726c1cbeecc0/pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java#L68)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

there's still few more of these line breaks (see here and below in the review)
</blockquote></details>

Done.

**Review by KFilipek — COMMENTED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/122)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

**Comment by KFilipek** [comment]
@lukaszstolarczuk Now should be fine

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/122)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)

**Pull request merged**
