### PR TITLE
utils: correct path to generated documentation for javadoc

### PR DESCRIPTION
**Pull request by KFilipek**
Previous approach cause generation of documentation separately for each project module.

This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/104)

### CODE REVIEW

**Comment by KFilipek** [comment]
Generated documentation was placed under: /home/${USER}/Development/work/pmemkv-java/target/site/apidocs/index.html

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/104)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[pom.xml, line 47 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/104#-MQCiEIY0QnymbcO-Fyx:-MQCiEIZ4qBmsfwMxvvS:bafjjjf) ([raw file](https://github.com/pmem/pmemkv-java/blob/2320dbc498810c3be4e8bac6259e2ca7379b0d26/pom.xml#L47)):*
> ```XML
>             </plugin>
>             <plugin>
>                 <groupId>org.apache.maven.plugins</groupId>
> ```

should we then keep this plugin in `pmemkv-binding/pom.xml` too? if yes, please update the version there (there's 3.0.0)

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/104)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[pom.xml, line 47 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/104#-MQCiEIY0QnymbcO-Fyx:-MQCj4mk1lACiKSHbK1y:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/2320dbc498810c3be4e8bac6259e2ca7379b0d26/pom.xml#L47)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

should we then keep this plugin in `pmemkv-binding/pom.xml` too? if yes, please update the version there (there's 3.0.0)
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/104#-:-MQClK3A6c6ylpefoLkQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/104)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[utils/docker/run-doc-update.sh, line 3 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/104#-MQGnywdBGmJ4uNG8DDX:-MQGnywdBGmJ4uNG8DDY:b-6no2mf) ([raw file](https://github.com/pmem/pmemkv-java/blob/64037130cbe604ecfcd78c5431051b551a64d42e/utils/docker/run-doc-update.sh#L3)):*
> ```Shell
> #!/usr/bin/env bash
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2018-2020, Intel Corporation
> ```

pls fix the license (2021 ;) )

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/104)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[utils/docker/run-doc-update.sh, line 3 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/104#-MQGnywdBGmJ4uNG8DDX:-MQHMcCn-ylaxqZM9-Py:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/64037130cbe604ecfcd78c5431051b551a64d42e/utils/docker/run-doc-update.sh#L3)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls fix the license (2021 ;) )
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/104)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)

___
*[utils/docker/run-doc-update.sh, line 3 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/104#-MQGnywdBGmJ4uNG8DDX:-MQHTCTg0SVefHbCb6T2:bo904p8) ([raw file](https://github.com/pmem/pmemkv-java/blob/64037130cbe604ecfcd78c5431051b551a64d42e/utils/docker/run-doc-update.sh#L3)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

uff, I can sleep now ;)

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/104)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[pom.xml, line 28 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/104#-MQRMZCn162ok8Sg0EIX:-MQRMZCn162ok8Sg0EIY:b-kanf92) ([raw file](https://github.com/pmem/pmemkv-java/blob/6e67932b837b7264b8e6c596704368fd02460996/pom.xml#L28)):*
<details><summary><i alt="summary">Quoted 18 lines of code…</i></summary>

> ```
> 
>         <plugins>
>             <plugin>
>                 <groupId>net.revelc.code.formatter</groupId>
>                 <artifactId>formatter-maven-plugin</artifactId>
>                 <version>2.11.0</version>
>                 <configuration>
>                     <configFile>${pom.basedir}/utils/eclipse-formatter-config.xml</configFile>
>                     <lineEnding>LF</lineEnding>
>                 </configuration>
>                 <executions>
>                     <execution>
>                         <goals>
>                             <goal>validate</goal>
>                         </goals>
>                     </execution>
>                 </executions>
>             </plugin>
> ```
</details>

Withespaces change is  not related to commit scope.

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/104)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[pom.xml, line 28 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/104#-MQRMZCn162ok8Sg0EIX:-MQS9I4p7DD3A-DJWHrz:b-556b0t) ([raw file](https://github.com/pmem/pmemkv-java/blob/6e67932b837b7264b8e6c596704368fd02460996/pom.xml#L28)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

> ```
> 
>         <plugins>
>             <plugin>
>                 <groupId>net.revelc.code.formatter</groupId>
>                 <artifactId>formatter-maven-plugin</artifactId>
>                 <version>2.11.0</version>
>                 <configuration>
>                     <configFile>${pom.basedir}/utils/eclipse-formatter-config.xml</configFile>
>                     <lineEnding>LF</lineEnding>
>                 </configuration>
>                 <executions>
>                     <execution>
>                         <goals>
>                             <goal>validate</goal>
>                         </goals>
>                     </execution>
>                 </executions>
>             </plugin>
> ```
Withespaces change is  not related to commit scope. 
</blockquote></details>

I've added plugin below and formatted nearby code

**Review by karczex — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/104#-:-MRPYp3v0sQskm32qPtl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)

**Pull request merged**
