### PR TITLE
Changelog: update changelog for pmemkv-java 1.0.1 release

### PR DESCRIPTION
**Pull request by KFilipek**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/107)

### CODE REVIEW

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/107#-:-MRQIc8S8mQMOIer-GR6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/107#-:-MRTxZuO6BZ2bVxGuxz6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/107)* status: all files reviewed, 6 unresolved discussions (waiting on @KFilipek)

___
*[ChangeLog, line 1 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/107#-MRU2dxE2_nNwSdaCSqd:-MRU2dxE2_nNwSdaCSqe:bdyi9pk) ([raw file](https://github.com/pmem/pmemkv-java/blob/c6174056b5b1af403502bd8cb677b089be350dbc/ChangeLog#L1)):*
> ```
> Tue Jan 19 2020 Krzysztof Filipek <krzysztof.filipek@intel.com>
> ```

right before doing the release we have to update **weekday**, the date and the person making the release

also, 2021 ;)
___
*[ChangeLog, line 5 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/107#-MRU37wUBsXRHpWqudXr:-MRU37wUBsXRHpWqudXs:bjozygv) ([raw file](https://github.com/pmem/pmemkv-java/blob/c6174056b5b1af403502bd8cb677b089be350dbc/ChangeLog#L5)):*
> ```
> 	* Version 1.0.1
> 
> 	Major changes:
> ```

can we even do "major" changes? in a patch release ;) let's make it perhaps: minor changes and bug fixes. And pleasegroup them all accordingly
___
*[ChangeLog, line 7 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/107#-MRU3cvQ5293HKUwl1vu:-MRU3cvQ5293HKUwl1vv:b-xuxpcg) ([raw file](https://github.com/pmem/pmemkv-java/blob/c6174056b5b1af403502bd8cb677b089be350dbc/ChangeLog#L7)):*
> ```
> 	Major changes:
> 	- simplify compilation
> 	- fix Maven modules locations
> ```

locations -> paths, and perhaps "relative paths"
___
*[ChangeLog, line 9 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/107#-MRU3rJO1NwHUPK8PNrb:-MRU3rJO1NwHUPK8PNrc:b-luya6z) ([raw file](https://github.com/pmem/pmemkv-java/blob/c6174056b5b1af403502bd8cb677b089be350dbc/ChangeLog#L9)):*
> ```
> 	- fix Maven modules locations
> 	- generated Jar file includes dependencies
> 	- every example is compiled to runnable Jar
> ```

perhaps `examples are compiled into runnable Jar` (side question "jar" or "Jar"? or even "JAR"?)
___
*[ChangeLog, line 13 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/107#-MRU32qI6jZtaK12RF8j:-MRU32qI6jZtaK12RF8k:bkjgahd) ([raw file](https://github.com/pmem/pmemkv-java/blob/c6174056b5b1af403502bd8cb677b089be350dbc/ChangeLog#L13)):*
> ```
> 
> 	Minor changes:
> 	- readme updates
> ```

that's really minor, I'd remove it
___
*[ChangeLog, line 14 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/107#-MRU4G7e0KBkPGNCC-DV:-MRU4G7f-cc55lK73Juj:b-h2snfb) ([raw file](https://github.com/pmem/pmemkv-java/blob/c6174056b5b1af403502bd8cb677b089be350dbc/ChangeLog#L14)):*
> ```
> 	Minor changes:
> 	- readme updates
> 	- javadoc generation fix
> ```

if you talking about my fix then it was in a docker scripts, so it's not relevant to the release, but was is worth mention is that examples do not generate javadoc (your fix from some time ago) - I'd say here about that, e.g. `fix: don't generate javadocs for examples`

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/107)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[ChangeLog, line 1 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/107#-MRU2dxE2_nNwSdaCSqd:-MRUQNxNAlTRr2yxmYuM:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/c6174056b5b1af403502bd8cb677b089be350dbc/ChangeLog#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

right before doing the release we have to update **weekday**, the date and the person making the release

also, 2021 ;)
</blockquote></details>

Done.
___
*[ChangeLog, line 5 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/107#-MRU37wUBsXRHpWqudXr:-MRUQOnO-8L0OwL1rsVF:b-owfz65) ([raw file](https://github.com/pmem/pmemkv-java/blob/c6174056b5b1af403502bd8cb677b089be350dbc/ChangeLog#L5)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

can we even do "major" changes? in a patch release ;) let's make it perhaps: minor changes and bug fixes. And pleasegroup them all accordingly
</blockquote></details>

Why not? Total change of building is not comparable to typo fix.
___
*[ChangeLog, line 7 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/107#-MRU3cvQ5293HKUwl1vu:-MRUX-u59fcBZR8UtbRR:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/c6174056b5b1af403502bd8cb677b089be350dbc/ChangeLog#L7)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

locations -> paths, and perhaps "relative paths"
</blockquote></details>

Done.
___
*[ChangeLog, line 9 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/107#-MRU3rJO1NwHUPK8PNrb:-MRUWcM51ySO-92E5dcw:bnp972s) ([raw file](https://github.com/pmem/pmemkv-java/blob/c6174056b5b1af403502bd8cb677b089be350dbc/ChangeLog#L9)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps `examples are compiled into runnable Jar` (side question "jar" or "Jar"? or even "JAR"?)
</blockquote></details>

"examples are compiled into runnable Jar" is semantically wrong
___
*[ChangeLog, line 13 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/107#-MRU32qI6jZtaK12RF8j:-MRUX0ivE3SNJML_dcRa:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/c6174056b5b1af403502bd8cb677b089be350dbc/ChangeLog#L13)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

that's really minor, I'd remove it
</blockquote></details>

Done.
___
*[ChangeLog, line 14 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/107#-MRU4G7e0KBkPGNCC-DV:-MRUXDag8iEDk24zVhsV:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/c6174056b5b1af403502bd8cb677b089be350dbc/ChangeLog#L14)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

if you talking about my fix then it was in a docker scripts, so it's not relevant to the release, but was is worth mention is that examples do not generate javadoc (your fix from some time ago) - I'd say here about that, e.g. `fix: don't generate javadocs for examples`
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/107)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[ChangeLog, line 5 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/107#-MRU37wUBsXRHpWqudXr:-MRUlN45CN_ACpigAdcJ:b-wo2829) ([raw file](https://github.com/pmem/pmemkv-java/blob/c6174056b5b1af403502bd8cb677b089be350dbc/ChangeLog#L5)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Why not? Total change of building is not comparable to typo fix.
</blockquote></details>

I totally agree, it just shouldn't be advertised as "major change" in a patch release ;) "Improvements" seems good.

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/107)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

**Review by igchor — COMMENTED** [review]
Please make this PR to stable-1.0

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/107#-:-MVRi-0m4SGggKZnr3Kv:bwxg8cp)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/107#-:-MVRn8Yo88xBimosVBK2:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

**Pull request merged**
